In [ ]:
Array Operations

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
add_result=np.add(a,b)
print("Addition:",add_result)

Addition: [5 7 9]


Subtraction

In [ ]:
sub_result=np.subtract(a,b)
print("Subtraction:",sub_result)

Subtraction: [-3 -3 -3]


Multiplication

In [ ]:
mul_result=np.multiply(a,b)
print("Multiplication:",mul_result)

Multiplication: [ 4 10 18]


Division

In [ ]:
div_result=np.divide(a,b)
print("Division:",div_result)

Division: [0.25 0.4  0.5 ]


Array Reshapping

In [ ]:
import numpy as np
array = np.arange(12)
print("Original array:",array)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


reshape 2D array

In [ ]:
reshaped_array=array.reshape((3,4))
print("Reshaped to 3*4:\n",reshaped_array)

Reshaped to 3*4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


reshape 3D array

In [ ]:
reshaped_array_3d=array.reshape((2,3,2))
print("Reshaped to 2*3*2:\n",reshaped_array_3d)

Reshaped to 2*3*2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


index and slicing

In [ ]:
create 2D array

In [ ]:
import numpy as np
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:\n",array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


access element at(1,2)

In [ ]:
element=array_2d[1,2]
print("Element at (1,2):",element)

Element at (1,2): 6


slicing a subarray (row 1 to 2,columns 0 to 1)

In [ ]:
subarray = array_2d[1:3,0:2]
print("Sliced subarray:\n",subarray)

Sliced subarray:
 [[4 5]
 [7 8]]


access a column (all rows,column 1)

In [ ]:
column = array_2d[:,1]
print("Column1:",column)

Column1: [2 5 8]


Statistical operations

create an array

In [ ]:
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(array)
print("Mean:",mean)

Mean: 5.5


calculate median

In [ ]:
median = np.median(array)
print("Median:",median)

Median: 5.5


calculate standard deviation

a

In [ ]:
std_dev = np.std(array)
print("Standard Deviation:",std_dev)

Standard Deviation: 2.8722813232690143


find minimum and maximum values

In [ ]:
min_val = np.min(array)
max_val = np.max(array)
print("Minimum value:",min_val)

Minimum value: 1


In [ ]:
min_val = np.min(array)
max_val = np.max(array)
print("Minimum value:",min_val)
print("Maximum value:",max_val)

Minimum value: 1
Maximum value: 10
